version: '3.8'

services:
  # Database Service
  mysql-db:
    image: mysql:8.0
    container_name: inai-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Vlen2005
      MYSQL_DATABASE: inai_app
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # Pastikan file init.sql ada di root folder
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pVlen2005"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend Service
  main-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: inai-go-backend
    restart: always
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - DB_MYSQL_HOST=mysql-db
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_USER=root
      - DB_MYSQL_PASSWORD=Vlen2005
      - DB_MYSQL_NAME=inai_app
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      mysql-db:
        condition: service_healthy

  # Frontend Service
  main-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: inai-react-frontend
    ports:
      - "80:80"
    depends_on:
      - main-backend

volumes:
  mysql_data: